import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login | E-Prioritas",
  description: "Generated by create next app",
};

const layout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return <div className="grid min-h-svh lg:grid-cols-2">{children}</div>;
};

export default layout;
