# networks:
#   e-prioritas-net:
#     driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
      - ./tsconfig.json:/app/tsconfig.json
      - ./postcss.config.mjs:/app/postcss.config.mjs
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    # networks:
    #   - e-prioritas-net

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - e-prioritas-net
