# Base image
FROM node:24-alpine

WORKDIR /app

# Install runtime deps (buat prisma, bcrypt, crypto, dll)
RUN apk add --no-cache \
  libc6-compat \
  openssl \
  libssl3 \
  libstdc++ \
  python3 \
  make \
  g++

# Install pnpm
RUN npm install -g pnpm

# Copy package files
COPY ../package.json ../pnpm-lock.yaml ./

# Install dependencies (dev deps juga ikut)
RUN pnpm install

# Copy configs & source
COPY ../tsconfig.json ../postcss.config.mjs ./
COPY ../prisma ./prisma
COPY ../src ./src
COPY ../public ./public

# Generate Prisma client
RUN pnpm prisma generate

EXPOSE 3000

# Dev mode (hot reload)
CMD ["pnpm", "dev"]
