
# Base image
FROM node:22-alpine
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package files & configs
COPY ../package.json ../pnpm-lock.yaml ./
COPY ../tsconfig.json ../postcss.config.mjs ./

# Approve ignored built dependencies & install
ENV PNPM_APPROVE_BUILDS=true
RUN pnpm install

# Copy Prisma & generate client
COPY ../prisma ./prisma
RUN pnpm prisma generate

# Copy source code & public folder
COPY ../src ./src
COPY ../public ./public

# Expose port Next.js
EXPOSE 3000

# Command untuk development (hot reload)
CMD ["pnpm", "dev"]
